spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
  application:
    name: CDP
server:
  port: 8081
sqlite:
  url: jdbc:sqlite:/home/almerlinux/Microservices/db/testdbs/metadata/metadata.db

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
